# Generated by Django 4.2 on 2023-05-26 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_message_recipient_alter_message_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
