# Generated by Django 4.2 on 2023-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_payment_id_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_github",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_linkedin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_twitter",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_website",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_youtube",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="billing_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
