# Generated by Django 4.2 on 2023-05-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_remove_profile_bio_remove_profile_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
        migrations.RemoveField(
            model_name="profile",
            name="created",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
