# Generated by Django 4.2 on 2023-04-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="num_rooms",
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_type",
            field=models.CharField(
                choices=[
                    ("budget", "Budget"),
                    ("mid-range", "Mid-Range"),
                    ("luxury", "Luxury"),
                    ("resort", "Resort"),
                ],
                default="budget",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="location",
            field=models.CharField(
                choices=[
                    ("Dhaka", "Dhaka"),
                    ("Chittagong", "Chittagong"),
                    ("Sylhet", "Sylhet"),
                    ("Khulna", "Khulna"),
                    ("Barisal", "Barisal"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms_hotel",
                to="hotels.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single"),
                    ("DOUBLE", "Double"),
                    ("TWIN", "Twin"),
                    ("FAMILY", "Family"),
                ],
                max_length=50,
            ),
        ),
    ]
