# Generated by Django 4.2 on 2023-05-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_remove_hotel_num_rooms_hotel_hotel_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_room",
                to="hotels.room",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="hotel",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_hotel",
                to="hotels.hotel",
            ),
        ),
    ]
