# Generated by Django 4.2 on 2023-04-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats_vehicle",
                to="tickets.travel",
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="destination",
            field=models.CharField(
                choices=[
                    ("Dhaka", "Dhaka"),
                    ("Chittagong", "Chittagong"),
                    ("Sylhet", "Sylhet"),
                    ("Khulna", "Khulna"),
                    ("Rajshahi", "Rajshahi"),
                    ("Barisal", "Barisal"),
                    ("Rangpur", "Rangpur"),
                    ("Comilla", "Comilla"),
                    ("Narayanganj", "Narayanganj"),
                    ("Jessore", "Jessore"),
                    ("Savar", "Savar"),
                    ("Mymensingh", "Mymensingh"),
                    ("Tangail", "Tangail"),
                    ("Gazipur", "Gazipur"),
                    ("Bogra", "Bogra"),
                    ("Nawabganj", "Nawabganj"),
                    ("Narsingdi", "Narsingdi"),
                    ("Joypurhat", "Joypurhat"),
                    ("Saidpur", "Saidpur"),
                    ("Sirajganj", "Sirajganj"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="origin",
            field=models.CharField(
                choices=[
                    ("Dhaka", "Dhaka"),
                    ("Chittagong", "Chittagong"),
                    ("Sylhet", "Sylhet"),
                    ("Khulna", "Khulna"),
                    ("Rajshahi", "Rajshahi"),
                    ("Barisal", "Barisal"),
                    ("Rangpur", "Rangpur"),
                    ("Comilla", "Comilla"),
                    ("Narayanganj", "Narayanganj"),
                    ("Jessore", "Jessore"),
                    ("Savar", "Savar"),
                    ("Mymensingh", "Mymensingh"),
                    ("Tangail", "Tangail"),
                    ("Gazipur", "Gazipur"),
                    ("Bogra", "Bogra"),
                    ("Nawabganj", "Nawabganj"),
                    ("Narsingdi", "Narsingdi"),
                    ("Joypurhat", "Joypurhat"),
                    ("Saidpur", "Saidpur"),
                    ("Sirajganj", "Sirajganj"),
                ],
                default="Dhaka",
                max_length=100,
            ),
        ),
    ]
