# Generated by Django 4.2 on 2023-04-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_seat_vehicle_alter_travel_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="arrival_time",
            field=models.DateTimeField(null=True),
        ),
    ]
