# Generated by Django 4.2 on 2023-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_alter_travel_arrival_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="arrival_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
