# Generated by Django 4.2 on 2023-05-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_message_recipient_alter_message_sender"),
        ("tickets", "0005_travel_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travel",
            name="payment",
        ),
        migrations.AddField(
            model_name="ticket",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_ticket",
                to="users.payment",
            ),
        ),
    ]
